### PR TITLE
Points decrement for wrong answers

### LINKED ISSUE #1: Make it so that every wrong answer removes 100 points
Then all you have to do to calculate the number of wrong answers is:
```js
((total amount of questions * 100) - score) / 100
```

So if I had 15 questions and my score was 1000 then:
```js
((15 * 100) - 1000) / 100
```
would give you 5. Then `15 - 5 = 10`. So 5 wrong answers and 10 correct answers.

Okay so it's a bit complicated but I think this could be an interesting game mechanic.

### PR DESCRIPTION
**Pull request by BrajBliss**
# Related Issue/Addition to code

- Fixes #1 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change required a documentation update

# Proposed Changes

- Added a function that reduces the points by 100 and if the user reaches zero, it will stay on zero and not add negative scores.
- Documented it in the Rules and fixed a typo.

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by BrajBliss** [comment]
One thing though, if the prettier formatting is not what you want (_it replaced the double quotes with single quotes, whitespace, etc, that is why it shows so many changes_), I can re-format by making another commit.

**Comment by KendallDoesCoding** [comment]
> One thing though, if the prettier formatting is not what you want (_it replaced the double quotes with single quotes, whitespace, etc, that is why it shows so many changes_), I can re-format by making another commit.

Yeah, no worries. I use that extension too!

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
Hey Vrindavan,

Thanks a lot for your contribution!!

Looks good, only issue I got is that if the first question goes wrong it doesn't minus any points, ideally it should -100 even for the first question, and then it ads back to positive once you get a question right? What do you think about that.

Also, I see you changed the button colors, it looks much better now, only issue is this color doesn't look too nice now, can you change it a little bit? 
image


Thanks a ton,
Kendall Does Coding

**Comment by BrajBliss** [comment]
Oh sorry, I pressed the review button again. Anyway, that is weird because I did not change the colors at all. I just added the function in the js file and rules in the rules file.
I can make it so that it reduces points even on the first question but before I do that: can you tell me if you want the lowest score to reach -100 or even lower?

**Comment by KendallDoesCoding** [comment]
> Oh sorry, I pressed the review button again. Anyway, that is weird because I did not change the colors at all. I just added the function in the js file and rules in the rules file.

Oh sorry, I got confused, you didn't change the colors, dw about it.

> I can make it so that it reduces points even on the first question but before I do that: can you tell me if you want the lowest score to reach -100 or even lower?

If the person gets all the questions wrong, per question it -100 so if they get 15 questions wrong -1500, if it's a 10 question quiz and they get 5 wrong and 5 correct, score will be zero. Let's see how that would work out.

**Review by BrajBliss — COMMENTED** [review]
I have removed the 0 cap so now score can go below zero and removed that from rules also.

**Comment by KendallDoesCoding** [comment]
> I have removed the 0 cap so now score can go below zero and removed that from rules also.

Works perfectly. Thanks for your contribution.

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Hey @vrindavan , I require this done for all the quizzes, which can be seen in https://quiz.kendalldoescoding.gq/topics/ you did it only for the main one.

**Pull request merged**
