### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by sunny2329**
# Related Issue/Addition to code

- #53 

## Type of change
 Added favicon

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Proposed Changes

- Added favicon image in images folder.

- Edited the code to add the favicon image in index.html 

# Additional Info

- any additional info for context

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

# Screenshots

|         Original         |         Updated          |
| :----------------------: | :----------------------: |
| \*\*
Screenshot (63)
 | ** Screenshot (62) ** |

### CODE REVIEW

**Review by KendallDoesCoding — COMMENTED** [review]
Looks good.

>  It would also be nice that per quiz, for example Tech Quiz, we put a laptop as the favicon, per quiz different favicon?

Can you do this?

**Comment by sunny2329** [comment]
Sure.

**Comment by KendallDoesCoding** [comment]
Any updates @sunny2329?

**Comment by sunny2329** [comment]
Sorry but I am stuck with my end semester papers.

**Comment by KendallDoesCoding** [comment]
> Sorry but I am stuck with my end semester papers.

Hope you did well in them.. Any update?

**Comment by KendallDoesCoding** [comment]
Someone has begun work on this issue.

**Pull request closed without merging**
