### PR TITLE
Categories Added

### PR DESCRIPTION
**Pull request by KrishJ4856**
Quiz Categories Added

# Screenshots

**Before:**

[](https://postimg.cc/QH05MQJh)

[](https://postimg.cc/G9Mh8qV7)

**After:**

[](https://postimg.cc/bd1rMy2b)

### CODE REVIEW

**Comment by KrishJ4856** [comment]
Hey @KendallDoesCoding I am extremely sorry for the delay, I have been making few mistakes with commits and PRs.
I was all confused about how to find solutions to the mistakes I made hence I am raising a new PR with all the necessary changes. Please have a look and once again I am sorry for the inconvenience.

**Comment by KendallDoesCoding** [comment]
> Hey @KendallDoesCoding I am extremely sorry for the delay, I have been making few mistakes with commits and PRs. I was all confused about how to find solutions to the mistakes I made hence I am raising a new PR with all the necessary changes. Please have a look and once again I am sorry for the inconvenience.

No worries bro.

**Comment by KendallDoesCoding** [comment]
Will have a look in a bit.

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
Perfect, but after the categories, there is extra place left below by a lot, can you remove that not required space. Thanks

**Comment by KrishJ4856** [comment]
Done. I have removed the height given to `container` which was set to `200vh`.

**Review by KendallDoesCoding — COMMENTED** [review]
Only "Games" & "Festivals" have a solid background and not a gradient one, can you make them a gradient background.

Go to this website:
https://cssgradient.io/gradient-backgrounds/

Any background from the following will work:
- Grabient
- Gradient Hunt
- CoolHue

**Comment by KrishJ4856** [comment]
Sure, Done. 
Do you think any more changes are needed? 
I would be more than happy to contribute to the project.

**Review by KendallDoesCoding — APPROVED** [review]
Perfect!

**Comment by KendallDoesCoding** [comment]
Thanks for your contribution @KrishJ999!!

**Comment by KrishJ4856** [comment]
Welcome 😀

**Pull request merged**
