### PR TITLE
Fix: Play music in background instead of redirecting to YouTube

### LINKED ISSUE #39: Play music in background instead of redirecting to YouTube
Refer to: https://www.tutorialspoint.com/How-to-add-background-music-in-HTML#:~:text=The%20HTML%20tag%20is,play%20music%20in%20the%20background.

### PR DESCRIPTION
**Pull request by aaryansr26**
Fixes #39 
## Type of change
Added audio 
Please delete options that are not relevant.

- [x] Bug fix (Created an option to play music in background)
- [x] New feature (Added Volume on and Volume Off Buttons to control music playing) 

# Proposed Changes

- Added music folder in the main directory with the music in mp3 format
- Gave option of Volume On/Volume Off Buttons and give the control to play music to the users. 

# Additional Info- 
Instead of playing music in the background from the start, we can give user the control to turn on/off music whenever they want.

### CODE REVIEW

**Comment by aaryansr26** [comment]
Hey @KendallDoesCoding, this PR is ready for review!

**Review by KendallDoesCoding — COMMENTED** [review]
It works on the main page, but not on the quiz pages.. It must be added to all game.html files (but in the game.html files, make the buttons slightly small)

**Comment by aaryansr26** [comment]
Can you give me any help regarding this matter? @KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
> Can you give me any help regarding this matter? @KendallDoesCoding

Sure. I will get it done.

**Comment by KendallDoesCoding** [comment]
@aaryansr26 I've got the music autoplaying on each quiz, but if you reload the page it stops playing. If I load the page then close the website then reopen the page, then it plays. Only doesn't play on reload. Can you fix that?

**Comment by aaryansr26** [comment]
I'll try @KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
> I'll try @KendallDoesCoding

Thanks.. Otherwise, I will merge.

**Comment by aaryansr26** [comment]
Hey bro! I found in stackoverflow about a trick we can use to play audio automatically @KendallDoesCoding 
```

window.onload = function() {
    document.getElementById("audioplayer").play();
}
```
- Remove the autoplay attribute from the audio tag and add this as a script in every game.html page

**Comment by aaryansr26** [comment]
Generally this settings are blocked in a lot of modern browsers, that's why we can't play audio after refreshing! 

image

**Comment by KendallDoesCoding** [comment]
> Hey bro! I found in stackoverflow about a trick we can use to play audio automatically @KendallDoesCoding
> 
> ```
> 
> window.onload = function() {
>     document.getElementById("audioplayer").play();
> }
> ```
> 
> * Remove the autoplay attribute from the audio tag and add this as a script in every game.html page

Can you please make these changes?

**Comment by KendallDoesCoding** [comment]
> Generally this settings are blocked in a lot of modern browsers, that's why we can't play audio after refreshing!
> 
> image

It's active on my computer but it's not playing when refreshing.

**Comment by aaryansr26** [comment]
> > Hey bro! I found in stackoverflow about a trick we can use to play audio automatically @KendallDoesCoding
> > ```
> > 
> > window.onload = function() {
> >     document.getElementById("audioplayer").play();
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * Remove the autoplay attribute from the audio tag and add this as a script in every game.html page
> 
> Can you please make these changes?

This is also not working when we are refreshing the page

**Comment by KendallDoesCoding** [comment]
Thanks for your contribution @aaryansr26.

**Pull request merged**
