### PR TITLE
Feat: Add computer parts quiz.

### LINKED ISSUE #3: Quiz Topic: Ram/Computer Parts
Can add a bunch of questions about Ram/Computer Parts

RAM QUIZ: https://letsfindcourse.com/computer-fundamentals-mcq/ram-mcq-questions-and-answers#:~:text=Explanation%3A%20RAM%20Stands%20for%20Random%20Access%20Memory.
COMPUTER PARTS QUIZ: need to do research

### PR DESCRIPTION
**Pull request by MOHDNEHALKHAN**
@KendallDoesCoding    #3  Solved
Added computer parts quiz in the code.

### CODE REVIEW

**Review by KendallDoesCoding — COMMENTED** [review]
Looks good!

I request you to please add the quiz in Topics page, once done will merge.

**Comment by MOHDNEHALKHAN** [comment]
> Looks good!
> 
> I request you to please add the quiz in Topics page, once done will merge.

Can I add in Technology div after programming_language anchor tag 
Screenshot 2023-07-26 172137

**Comment by KendallDoesCoding** [comment]
> > Looks good!
> > I request you to please add the quiz in Topics page, once done will merge.
> 
> Can I add in Technology div after programming_language anchor tag Screenshot 2023-07-26 172137

yes,

**Comment by MOHDNEHALKHAN** [comment]
@KendallDoesCoding  
Completed the task 👍🏼

**Review by KendallDoesCoding — APPROVED** [review]
LGTM ✔️

**Comment by KendallDoesCoding** [comment]
Thanks for your contribution @MOHDNEHALKHAN!!

**Pull request merged**
