### PR TITLE
[MERGED] Rework, breaking changes

### LINKED ISSUE #16: Improve responsiveness
UI breaks at 14' and less, make the font as well as the size of the elements responsive

### LINKED ISSUE #22: Major restructure of folders, files, etc.
Currently, for every quiz I have a folder, in which includes the suggestion, end, game, rules directory. Although it gets very inconvenient for contributors and me personally to make edits to all the quizzes at once.

The reason I did this was so the website url is linked backed to the quiz you were playing it, but ig that's not really required, **so we can link the suggestion and end back to the main directory.**

Although, for the game directory, the questions change per quiz (common sense) and the game.js in that directory have the questions listed, **so would it be possible that in the main js file, to const a bunch of elements for the respective quizzes and link back the element of the quiz somehow?** I'm not good at JS so idk if this is possible lol.

Rules also change for every quiz, so should we const the rules page via JS too?

Other suggestions will be very appreciated.

cc: @vrindavan @TechStudent10

### LINKED ISSUE #23: [BUG] Website not opening locally
When I try to open the website locally, using a VS code extension called Liveserver, I get the error `cannot get route`.

### LINKED ISSUE #30: [BUG] Categories not opening up
For some reason the categories are not opening up in the dropdown, so right now only one quiz is playable (all are u need to have that quizzes individual link)

### PR DESCRIPTION
**Pull request by Hachikoi-the-creator**
# Related Issue/Addition to code

Fixes #16 
Fixes #22 
Fixes #23 
Fixes #30 

- Totally new file layout(not sure how to phrase it)
- Merged all the styles in 2 css files
- Merged all the .js files in modules & implemented a new Class for code reusability
- Fixed the onClick handler in /pages/topics.html
- Moved all the data to their own js file & using an index.js to import them all and export theme easily
	- new naming convention whit the exports ex: footballQA = All the data needed for /football/game.html
- Now every /pages/*/game.html has a little bit of JS on top, since it was the best approach I could think of, while also improving the perfomance
- Litle improvement in markdown in pages/rules.html
- Also changed hwdyk to kendall_quiz, hope it's not a problem

## Type of change

[live branch](https://8koi-rework-branch.netlify.app/)

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Proposed Changes

- improve sintax in:
	- pages/rules.html
	- pages/highscores.html 
	- pages/rate.html  
- Add a cute little favicon to all html files
- In main quiz change the position of the current answers, since every answer is in index[1] or just suffle them all in the QuizClass.js

# Additional Info

- Now every game.html file wil have a little script on top, to avoid creating N files whit just 7 lines of code

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Dev notes
Even tho it was a lot of work, I truly loved how consistent you where in the styling and classes naming, really makes the difference!

### CODE REVIEW

**Comment by Hachikoi-the-creator** [comment]
This pretty much covers issues 16, 23 and 22
I got a little too exited lol

**Comment by KendallDoesCoding** [comment]
Woah, that's a huge PR. 301 files, and it covers 3 issues. Thanks a lot! I will review and get back to you.

**Review by KendallDoesCoding — COMMENTED** [review]
It looks really good. But what happened to the main quiz.. I see that the main quiz just takes you to Browsers Quiz.
Main Quiz Preview: https://quiz.kendalldoescoding.tech/game/

> Add a cute little favicon to all html files
I cannot see the favicon that you've said you added in Proposed Changes.

**Comment by KendallDoesCoding** [comment]
> It looks really good. But what happened to the main quiz.. I see that the main quiz just takes you to Browsers Quiz. Main Quiz Preview: https://quiz.kendalldoescoding.tech/game/
> 
> > Add a cute little favicon to all html files
> > I cannot see the favicon that you've said you added in Proposed Changes.

Awaiting your reply on this @Hachikoi-the-creator

**Comment by Hachikoi-the-creator** [comment]
I tried it on your deployment and sent me to browsers quiz, so I assumed that's how it worked, will check and add it!

**Comment by Hachikoi-the-creator** [comment]
oh if I do another PR just adds itself to this (context)? nice
I found the quiz you were talking about! @KendallDoesCoding 
hope you like the improvements!

**Comment by KendallDoesCoding** [comment]
> oh if I do another PR just adds itself to this (context)? nice I found the quiz you were talking about! @KendallDoesCoding hope you like the improvements!

coz you updated the stuff to the same branch!!

**Review by KendallDoesCoding — COMMENTED** [review]
Looks good! But, would it be possible to include the question number on the side of "Question text" like in the original website?

**Comment by Hachikoi-the-creator** [comment]
Got into a bootcamp and finally got some free time, it was easier than expected lol

**Comment by Hachikoi-the-creator** [comment]
what about adding mongoDB? and updating the highscores to show top5 of every category? that'd be sick!

**Comment by KendallDoesCoding** [comment]
> what about adding mongoDB? and updating the highscores to show top5 of every category? that'd be sick!

can you make a issue (feature request) on this?

**Review by KendallDoesCoding — APPROVED** [review]
Perfect, but please resolve conflicts to go to merge. @Hachikoi-the-creator

**Comment by Hachikoi-the-creator** [comment]
I tried leaving ` package-lock.json ` exactly as it was and there's still conflicts, so no idea what to do to fix it.
and topics & style is for the changes I did to reuse CSS instead of copy&paste everything, or maybe the same weird thing whit ` package-lock.json` I don't know

+ Given how big the project is, to make future changes you need to clone the repo in desktop and then add it to vscode, otherwise the live server won't work, probably was the same problem before as well

**Comment by KendallDoesCoding** [comment]
I can't even merge from command line :(

**Comment by KendallDoesCoding** [comment]
I managed to commit the PR, but I couldn't make it so you committed all the files :(!

**Comment by KendallDoesCoding** [comment]
Hey @Hachikoi-the-creator ,

Sorry that it took almost a month for me to merge this. I was really busy.

I don't know how to thank you. This is such a amazing Pull Request, that I've needed to do from a long time. Thanks for putting in so much hard work!!

**Comment by Hachikoi-the-creator** [comment]
nono thanks for making the merge, I was really overwhelmed working whit C and needed something refreshing, this was so fun to do!

**Comment by KendallDoesCoding** [comment]
@Hachikoi-the-creator I just included your name in README.md for the big changes you did to this project. I'm going to begin work/adding more quizzes, etc on this project soon!

**Pull request merged**
