### PR TITLE
fixed the bug that was caused only option B to be correct

### LINKED ISSUE #35: [BUG] [URGENT] Always showing b option as correct even if incorrect. - URGENT ASSISTANCE REQUIRED
In the website I found one bug I don't know if the bug coming for me only. The bug is if we select the b option for any questions It is giving correct and that is also not the actual answer.

_Originally posted by @Darshanjaji in https://github.com/KendallDoesCoding/quiz/issues/32#issuecomment-1468048670_

### PR DESCRIPTION
**Pull request by TripleStarCodeHunter**
Closes #35 

- [ ] Bug fix (non-breaking change which fixes an issue)

This change fixes the bug that always specified option B as correct

# Proposed Changes

The number 2 was being passed to the checkAnswer method in the game.html files of all quizzes, hence option B was always chosen as correct. I changed that parameter to QuizInstance.answer to specify the correct answer.

### CODE REVIEW

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
Doesn't seem to be fixed.

**Comment by KendallDoesCoding** [comment]
actually, it works, but you haven't made the changes in all your files!

**Review by KendallDoesCoding — APPROVED** [review]
You just hadn't made the changes to the main game.html..

Thanks so much!!
It was such a small silly mistake haha

**Comment by TripleStarCodeHunter** [comment]
> You just hadn't made the changes to the main game.html..
> 
> Thanks so much!! It was such a small silly mistake haha

 I hadn't noticed that last file. Anyway glad I could help

**Comment by KendallDoesCoding** [comment]
> > You just hadn't made the changes to the main game.html..
> > Thanks so much!! It was such a small silly mistake haha
> 
> I hadn't noticed that last file. Anyway glad I could help

Yeah, no worries. Thanks once again!!

**Pull request merged**
