### PR TITLE
Remove min-width of choice-container

### PR DESCRIPTION
**Pull request by psjnek**
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Proposed Changes

- Remove min-width of choice-container to leave some space around it

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

# Screenshots

|         Original         |         Updated          |
| :----------------------: | :----------------------: |
| image | image |

### CODE REVIEW

**Comment by psjnek** [comment]
@KendallDoesCoding 
Could you take a look at my PR please?

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding Could you take a look at my PR please?

Hey. Can you explain what's the benefit of getting this done, as I can see no difference here.

**Comment by psjnek** [comment]
> > @KendallDoesCoding Could you take a look at my PR please?
> 
> Hey. Can you explain what's the benefit of getting this done, as I can see no difference here.

Sure. I attached a video to show my changes in action. I hope it helps.
[Screencast from 2023-06-03 21-01-06.webm](https://github.com/KendallDoesCoding/quiz/assets/94064167/ed5f342d-0793-490c-be74-830066434b36)

**Comment by KendallDoesCoding** [comment]
Oh, it makes the website more responsive. I understand now.. LGTM ✔️

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
@WebSnke - thanks for your contribution!

**Pull request merged**
