### PR TITLE
Fixed Music Button issue #68

### PR DESCRIPTION
**Pull request by NeevJewalkar**
# Related Issue/Addition to code
In the quiz, the button "Music Off" just sticks with the "Music On" button after clicking the off button. This results in the Music Off button being inactive.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# Proposed Changes
- Added `musicOffButton.style.display = 'none'`

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

# Screenshots
Original:
Screenshot 2023-07-29 at 6 46 58 PM

Updated:
Screenshot 2023-07-29 at 7 31 43 PM

### CODE REVIEW

**Review by KendallDoesCoding — DISMISSED** [review]
Perfect. Kindly make the changes for all the quizzes within the pages directory.

**Comment by NeevJewalkar** [comment]
Alright, is it fine if i rewrite the .js code for it to be updated to the ES6 version? It will help get rid of the DeepSource flow fail

**Comment by KendallDoesCoding** [comment]
> Alright, is it fine if i rewrite the .js code for it to be updated to the ES6 version? It will help get rid of the DeepSource flow fail

It doesn't matter if it fails, it's ok. But, yes you can go ahead.

**Comment by NeevJewalkar** [comment]
@KendallDoesCoding – Tried my best but Deepsource keeps complaining 😅, will close the issue related to this after the changes are approved.

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Looks good! Thanks for your contribution @NeevJewalkar

**Pull request merged**
