### PR TITLE
adding of points distribution

### LINKED ISSUE #4: [FEATURE REQUEST] Figure new points when answer correct/wrong for points distribution
For now, when the answer is right, a figure like +100 in green should so up above the points. After #1 is done, a figure like -100 should show for every wrong answer.

@TechStudent10, can you work on this/merge this with the PR of #1 ?

### PR DESCRIPTION
**Pull request by SyonKuppili**
Hey!
I've added the Points Distribution according to the issue assigned by you.
An animation is added whenever a person gets a right or a wrong answer (which is of +100 and -100.)
I'd also recommend we add a sound effect to this! 
Thanks, 
Syon

fixes #4

### CODE REVIEW

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
Great!

It made the other quizzes unplayable though, please add these changes to the other quizzes and make it work. Thanks.

**Comment by SyonKuppili** [comment]
I've added the changes so that it works for every quiz now!

**Review by KendallDoesCoding — COMMENTED** [review]
Looks good, but the animation is not inclusive of the bonus points and only for correct answer shows +100 and wrong shows -100.

Question: Do you think it should show the bonus points?
I think it should. Let me know what you think.

**Comment by SyonKuppili** [comment]
Agreed, I think so too. I'll get working on it.

**Comment by SyonKuppili** [comment]
hey, i found a bug in the point system. when the streak goes to 4, as an elif statement is missing, it resets the streak to 0. ill be fixing this as well, making a streak of 4 to give 300,
a streak of 6,7,8,9 to give 800 and so on.
is this fine?

**Comment by SyonKuppili** [comment]
Hey Kendall! The bonus points animation has been finished and is working well for all topics. Please let me know if you need any more changes!
Thanks, Syon

**Review by KendallDoesCoding — DISMISSED** [review]

**Comment by KendallDoesCoding** [comment]
Thanks for your contribution @SyonKuppili .. This has made a big impact in the project. Sorry for the delay in merging

**Pull request merged**
