### PR TITLE
Added Base Favicons for All pages except Topic Quizzes

### LINKED ISSUE #53: [FEAT] Add Favicon
Add a quiz favicon, maybe like a question mark or something?

### PR DESCRIPTION
**Pull request by ghost**
# Added Favicons to all pages except Topic Quizzes

## Added favicon.ico in /images/

- [x] New feature (non-breaking change which adds functionality)

# Proposed Changes

- Added favicon.ico

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

# Screenshots

## Original 
Screenshot 2023-07-26 at 11 13 33 PM

## Updated
Screenshot 2023-07-26 at 11 15 10 PM

### CODE REVIEW

**Review by KendallDoesCoding — COMMENTED** [review]
Looks good, please add the remaining favicon's for the quiz topics.

What is the .DS_Store file, can we get rid of it?

**Comment by ghost** [comment]
> Looks good, please add the remaining favicon's for the quiz topics.
> 
> 
> 
> What is the .DS_Store file, can we get rid of it?

oh yeah i forgot to remove the file, will work on the rest of the favicons tomorrow

**Comment by ghost** [comment]
I have a added the Favicons, and removed the .DS_Store

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Thanks for your contribution @NeevJewalkar

**Pull request merged**
